Bypass screenshot restriction
saucelabs/sauce-docs pull request #1096
Opened 2022-03-03 20:35 UTC by lauramthomas

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-03 20:47 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +If you test Android mobile apps on Sauce Labs real devices and you see a black screen in your live testing session, you might need to enable the **Bypass Screenshot Restriction**.
```suggestion
If you test Android mobile apps on Sauce Labs real devices and see a black screen in your live testing session, you might need to enable the **Bypass Screenshot Restriction**.
```

2022-03-03 20:50 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +* Automated - You can run automated tests on real devices but you will not be able to see video associated with those tests.
```suggestion
* Automated - You can run automated tests on real devices, but you will not be able to see video associated with those tests.
```

2022-03-03 20:50 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +* Android 7.0 and 8.0 - Video works but you can’t take a screenshot
```suggestion
* Android 7.0 and 8.0 - Video works, but you can’t take a screenshot
```

2022-03-03 20:51 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +Your ability to work around this setting to test depends on a few factors:
```suggestion
Your ability to work around this setting to test will depend on a few factors:
```

2022-03-03 20:53 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +In cases where you’re using a third party app, you might be able to test your data directly on that app using live testing on a web browser.
```suggestion
In cases where you’re using a third party app, you might be able to test your data directly on that app using [live testing on a web browser](/web-apps/live-testing/live-cross-browser-testing/).
```

2022-03-03 20:56 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +## Enable Bypass Screenshot Restriction
```suggestion

```

2022-03-03 20:59 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +6. Click **Back to App Selection** at the top to test your app.
I'd move this to the top

2022-03-03 20:59 UTC, kimsauce commented on docs/mobile-apps/live-testing/live-mobile-app-testing.md
> +| Bypass Screenshot Restriction <br/><p><span className="sauceDBlue">ANDROID ONLY</span></p> | Enable/disable Bypass Screenshot Restriction (not supported on apps uploaded to the legacy sauce storage
```suggestion
| Bypass Screenshot Restriction <br/><p><span className="sauceDBlue">ANDROID ONLY</span></p> | Enable/disable Bypass Screenshot Restriction (not supported on apps uploaded to the legacy sauce storage). If you're testing Android mobile apps on Sauce Labs and see a black screen in your live testing session, you might need to enable the <b>Bypass Screenshot Restriction</b>. This allows Sauce Labs to work around a setting on those apps that prevents screenshots or videos from being taken. However, there are other details to keep in mind. To effectively test apps that have this setting, see [Bypass Screenshot Restriction](/mobile-apps/features/bypass-screenshot). |
```

2022-03-03 21:00 UTC, kimsauce commented on docs/mobile-apps/features/bypass-screenshot.md
> +If you are testing your company’s proprietary app on a real device, you might be able to workaround the **FLAG_SECURE** setting by enabling **Bypass Screenshot Restriction** on that app under certain
```suggestion
If you are testing your company’s proprietary app on a real device, you might be able to work around the **FLAG_SECURE** setting by enabling **Bypass Screenshot Restriction** on that app under certain circumstances.
```

2022-03-03 21:00 UTC, kimsauce requested changes
Had a few suggestions!

2022-03-04 01:42 UTC, lauramthomas reviewed
Thanks for the feedback!

2022-04-06 10:54 UTC, lauramthomas reviewed
@kimsauce I made your changes a while back, but must have forgotten to tag you to approve the review. Oops.

2022-04-06 18:05 UTC, kimsauce commented
@aoleszyn , this is the **FLAG_SECURE** doc you were waiting on -- it has been published! Can you please let Wendy know in the Jira ticket?

2022-04-06 18:05 UTC, kimsauce approved these changes

2022-04-06 18:15 UTC, merged