DRAFT: Docs revamp
saucelabs/sauce-docs pull request #1102
Opened 2022-03-09 18:19 UTC by discombobulateme

Working in progress to revamp Docs page based on new design: https://www.figma.com/file/gxXWfTFbeSAESpVU0pGsly/Doc-style-changes?node-id=60%3A608

Several changes are being done including:
- [ ]  including variables files to create standard styles
- [ ] adding partial files to better organize the styles
- [ ] creating new classes to match design

2022-04-06 23:02 UTC, kimsauce requested changes
Not sure if it's just me -- I couldn't get the build to work :(
<img width="680" alt="Screen Shot 2022-04-06 at 3 57 00 PM" src="https://user-images.githubusercontent.com/56411016/162087036-c0f4046b-0d29-402e-b227-7a60e1110be4.png">

2022-04-07 08:54 UTC, discombobulateme commented
@kimsauce did you `npm install` ? packages need to be reinstall as it is using the breadcrumbs

2022-04-07 15:10 UTC, spider-sauce commented on src/css/admonitions.css
> +    color: var(--ds-red-600);
good use of variables 👍

2022-04-07 16:59 UTC, discombobulateme commented on src/css/fonts/stylesheet.css
> +    src: local('Proxima Nova Black'), local('ProximaNova-Black'),
Yes! I just couldn't find someone to actually give me the Sauce certificate number or... something like... so I added the font face

2022-04-07 16:59 UTC, discombobulateme commented on docusaurus.config.js
>      {
:O thank you

2022-04-07 17:07 UTC, kimsauce approved these changes

2022-04-07 17:11 UTC, merged

2022-04-07 17:12 UTC, kimsauce commented
@discombobulateme @spider-sauce approved/merged!