email notification edits
saucelabs/sauce-docs pull request #1180
Opened 2022-04-19 16:57 UTC by LoryApiFortress

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-19 18:07 UTC, kimsauce commented on docs/api-testing/project-access.md
> +:::
Some repetition here. I suggest consolidating, @lauramthomas.

2022-04-19 18:07 UTC, kimsauce submitted a review, later dismissed
Left a recommendation

2022-04-25 13:24 UTC, lauramthomas requested changes
@LoryApiFortress I added my own edits to your review.

2022-04-25 13:39 UTC, lysannep approved these changes
Looks good!

2022-04-26 16:39 UTC, merged