Scheduler edits
saucelabs/sauce-docs pull request #1181
Opened 2022-04-19 17:01 UTC by LoryApiFortress

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-19 18:08 UTC, kimsauce commented on docs/api-testing/schedule-test.md
> +Schedule is available only for [published tests](/api-testing/quickstart/#publish-your-test).
```suggestion
The **Schedule** functionality is available only for [published tests](/api-testing/quickstart/#publish-your-test).
```

2022-04-19 18:10 UTC, kimsauce commented on docs/api-testing/schedule-test.md
> +1. From within the **Composer**, click the **Schedule** tab to access the Scheduler.<br/><img src={useBaseUrl('img/api-fortress/2021/02/scheduleTab.png')} alt="Schedule Tab"/>
@LoryApiFortress , I think we may have discussed before -- we should be using **Compose** and **Schedule** (not  **Composer** and **Scheduler**) to match the UI elements. 

You could also speak with the Growth Team to propose changing the UI elements to **Composer** and **Scheduler**.

2022-04-19 18:11 UTC, kimsauce submitted a review, later dismissed
Some recommendations

2022-04-25 12:35 UTC, lauramthomas requested changes
@LoryApiFortress I reviewed your changes and made some of my own.

2022-04-26 16:02 UTC, lauramthomas approved these changes

2022-04-26 16:15 UTC, merged