Update network-capture.md for consitency
saucelabs/sauce-docs pull request #1185
Opened 2022-04-20 19:10 UTC by linafarid

A few improvements for the sake of consistency.
- The word CLI is reserved in our docs for SauceCTL ,vUSB, etc. We generally refer to remote uploads as "REST API" not CLI. Customers, use different means to connect to our APIs and not necessarily via a CLI only.
- added link for NSURLConnection for consistency. Removed "some time ago" as I felt it to be redundant.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-21 12:10 UTC, aoleszyn approved these changes

2022-04-25 18:08 UTC, kimsauce approved these changes

2022-04-25 18:09 UTC, kimsauce commented on docs/mobile-apps/features/network-capture.md
> +2. Upload your mobile app to Sauce Labs [through our UI](/mobile-apps/app-storage/#uploading-apps-via-ui) or [our REST API](/mobile-apps/app-storage/#uploading-apps-via-rest-api).
@linafarid can you please apply this edit to the Audio Capture doc as well?

2022-04-25 18:09 UTC, kimsauce requested changes
One change requested

2022-05-23 08:29 UTC, discombobulateme approved these changes

2022-05-23 14:04 UTC, lysannep approved these changes

2022-05-23 14:24 UTC, merged