[WIP] Update SC env vars docs towards 4.8.0 release
saucelabs/sauce-docs pull request #1200
Opened 2022-04-25 19:38 UTC by waggledans

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-26 20:49 UTC, kimsauce commented on docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
> +* On MacOS and Linux, Sauce Connect Proxy looks for these variables, in this order:
```suggestion
* On macOS, Sauce Connect Proxy will use the proxy settings in Preferences/Network. Both proxy and PAC settings are supported.
* On macOS and Linux, Sauce Connect Proxy looks for these variables, in this order:
```

2022-04-26 20:50 UTC, kimsauce requested changes
minor change!

2022-04-27 10:38 UTC, lauramthomas approved these changes
I added a couple of edits to the note, but otherwise it looks good!

2022-04-27 17:16 UTC, kimsauce approved these changes

2022-04-27 19:38 UTC, merged