fixing broken link to Visual E2E WebDriverIO example tests
saucelabs/sauce-docs pull request #1213
Opened 2022-04-30 12:40 UTC by mattdsauce

### Description
fixing broken link to Visual E2E WebDriverIO example tests

### Motivation and Context
fixes a broken link (404)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-01 16:59 UTC, lauramthomas approved these changes

2022-05-03 17:51 UTC, kimsauce commented on docs/visual/e2e-testing/code-examples.md
>  * [Ruby](https://github.com/saucelabs-training/demo-ruby/tree/main/sauce-features/visual/basic)
```suggestion
* [Ruby](https://github.com/saucelabs-training/demo-ruby/tree/main/sauce-features/visual)
```

2022-05-03 17:51 UTC, kimsauce requested changes
Minor change

2022-05-04 05:28 UTC, kimsauce commented on docs/visual/e2e-testing/code-examples.md
>  * [Ruby](https://github.com/saucelabs-training/demo-ruby/tree/main/sauce-features/visual/basic)
Hi @mattdsauce , thanks again for submitting this PR! If this additional change looks ok to you, I'll go ahead and merge.

2022-05-04 08:36 UTC, mattdsauce commented
looks good, thanks!

2022-05-04 17:30 UTC, merged