[DEVX-1634] Add saucectl documentation for excludedTestFiles
saucelabs/sauce-docs pull request #1223
Opened 2022-05-04 23:11 UTC by tianfeng92

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-06 00:25 UTC, alexplischke approved these changes

2022-05-06 04:24 UTC, kimsauce requested changes
Should the wording for these be more consistent?

2022-05-07 04:21 UTC, kimsauce commented on docs/web-apps/automated-testing/testcafe/yaml.md
> +Excludes test files to skip the tests. Files are matched by shell pattern, e.g. the explicit name, file glob, or the location of the test files.
```suggestion
Excludes test files to skip the tests. Files are matched by shell pattern, such as the explicit name, file glob, or location of the test files.
```

2022-05-07 04:30 UTC, kimsauce commented on docs/web-apps/automated-testing/playwright/yaml.md
> +Excludes test files to skip the tests. Regex values are supported to indicate all files of a certain type or in a certain directory, etc.
@lysannep @tianfeng92 Can you take a look at this wording? 

```suggestion
Excludes test files to skip the tests. You can use regex values to indicate all files that match a specific value, such as a file name, type, or directory.
```

2022-05-07 04:30 UTC, kimsauce requested changes
A couple comments!

2022-05-09 20:08 UTC, kimsauce approved these changes

2022-05-09 21:02 UTC, merged