Minor Corrections to code sample
saucelabs/sauce-docs pull request #1251
Opened 2022-05-16 15:40 UTC by aoleszyn

### Description
Small code-related corrections ( incorrect quotation marks and missing comma)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-05-16 17:02 UTC, wswebcreation requested changes
Small remark

2022-05-16 17:02 UTC, wswebcreation commented on docs/mobile-apps/automated-testing/appium/real-devices.md
> +    "orientation" : "portrait",
This needs to be UPPERCASE, is for all times it's used in this doc

2022-05-19 15:01 UTC, wswebcreation approved these changes
LGTM, thanks!

2022-05-19 17:49 UTC, kimsauce approved these changes

2022-05-19 17:58 UTC, merged