Added vdc to "Importing a HAR File"
saucelabs/sauce-docs pull request #1306
Opened 2022-06-22 14:21 UTC by lauramthomas

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-22 14:49 UTC, lysannep approved these changes
✨ Looks good to me!

2022-06-23 09:38 UTC, LoryApiFortress requested changes

2022-06-23 09:38 UTC, LoryApiFortress commented on docs/api-testing/import-postman-collection.md
>  You can import a HAR (HTTP Archive) file into API Testing to automatically generate a functional test. Network Traffic Capture must be enabled to use this feature. See [Network Traffic Capture](/mobi
@lauramthomas we need to also mention this https://docs.saucelabs.com/insights/debug/#enabling-extended-debugging since it is required for VDC

2022-06-23 09:38 UTC, LoryApiFortress commented on docs/api-testing/import-postman-collection.md
> +## Importing a HAR File (RDC and VDC)
@lauramthomas does it worth to mention what RDC and VDC mean? it seems not all people knows the meaning

2022-07-14 17:25 UTC, LoryApiFortress approved these changes

2022-07-14 17:26 UTC, merged