Added "Load Testing" page to API Testing
saucelabs/sauce-docs pull request #1308
Opened 2022-06-22 23:45 UTC by lauramthomas

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-23 00:52 UTC, lysannep commented on docs/api-testing/load-testing.md
> +To stop a report before it is complete, click the **Stop** button.
```suggestion
To stop a report before it is complete, click **Stop**.
```

2022-06-23 01:02 UTC, lysannep submitted a review, later dismissed
@lauramthomas I noticed just one typo.

2022-06-23 09:00 UTC, LoryApiFortress requested changes

2022-06-28 16:10 UTC, LoryApiFortress commented
@lauramthomas please proceed with the push as per request in the Jira ticket and let me know when it is available in production. Thanks!

2022-07-01 17:36 UTC, spider-sauce approved these changes
👍

2022-07-01 17:40 UTC, merged