New Live Testing capability for Device Passcode
saucelabs/sauce-docs pull request #1358
Opened 2022-07-25 14:34 UTC by kristofmuhi

https://saucedev.atlassian.net/browse/MRE-543
Counterpart of https://docs.saucelabs.com/dev/test-configuration-options/#setupdevicelock

### Description
Added the new Device passcode capability to app Settings page. 

### Motivation and Context
Solves the problem of customers pinlocking our devices on Android.
 From now on, customers can setup the pincode by passing a boolean value for their native app tests.

When this checkbox is checked, before their test kicks in for Android, we are setting up the pincode for the customers. 
After test finishes we are removing the passcode
IF you dont have a passcode set on the device, certain apps cannot be launched without setting a pincode.
this enables certain mobile apps, which has strict security requirements to be launched. 

### Types of changes
[X] New feature (non-breaking change which adds functionality)

2022-07-27 19:20 UTC, lysannep requested changes

2022-07-27 19:20 UTC, lysannep commented on docs/mobile-apps/live-testing/live-mobile-app-testing.md
> +| Device Passcode <br/><p><span className="sauceDBlue">ANDROID ONLY</span></p> | Enable/disable setting up device passcode on the device. If you are testing an Android Mobile app which requires a Pas
```suggestion
| Device Passcode <br/><p><span className="sauceDBlue">Android Only</span></p> | Enable/disable the device passcode for Android apps. If your app requires a device passcode to launch, you can enable this setting to run your tests on a passcode-protected device. |
```

2022-07-28 16:13 UTC, kristofmuhi commented
@lysannep thanks, all change commited

2022-07-28 16:14 UTC, lysannep approved these changes
@kristofmuhi Thank you!

2022-08-01 13:18 UTC, merged