Document Cypress 10
saucelabs/sauce-docs pull request #1372
Opened 2022-08-01 21:39 UTC by alexplischke

### Description
Document Cypress 10.

2022-08-01 21:40 UTC, alexplischke commented on docs/web-apps/automated-testing/cypress/yaml-configuration/yaml-v1.md
> +<!-- TODO need to create a new Cypress 10 example first. -->
Reminder to self before merging.

2022-08-02 05:37 UTC, wswebcreation commented
@alexplischke 

I was just checking this and I understand that we can't mentioned every change from major Cypress versions here, but in V10 they deprecated the `config.json`, see [this](https://docs.cypress.io/guides/references/legacy-configuration#cypress-json) and replaced it with `cypress.config.js`, see [this](https://docs.cypress.io/guides/references/configuration).
It might be useful to also note that in our docs. What do you think?

2022-08-02 16:46 UTC, alexplischke commented
> @alexplischke
> 
> I was just checking this and I understand that we can't mentioned every change from major Cypress versions here, but in V10 they deprecated the `config.json`, see [this](https://docs.cypress.io/guides/references/legacy-configuration#cypress-json) and replaced it with `cypress.config.js`, see [this](https://docs.cypress.io/guides/references/configuration). It might be useful to also note that in our docs. What do you think?

It's just one of many changes though. The user absolutely _has_ to go through the [migration process](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0) that Cypress prescribes for Cypress 10. I would much rather put up a generic note. So let me do that at least 👍

2022-08-02 20:26 UTC, tianfeng92 requested changes

2022-08-02 20:26 UTC, tianfeng92 commented on docs/web-apps/automated-testing/cypress/yaml/v1.md
> +One or more paths to the Cypress test files to run for this suite. Regex values are supported to indicate all files of a certain type or in a certain directory, etc.
It should be glob pattern for `sepcPattern` and `excludeSpecPattern`. https://docs.cypress.io/guides/references/configuration#e2e

2022-08-02 20:26 UTC, tianfeng92 commented on docs/web-apps/automated-testing/cypress/yaml/v1alpha.md
> +One or more paths to the Cypress test files to run for this suite, if not otherwise specified explicitly in `cypress.json`. Regex values are supported to indicate all files of a certain type or in a
hmm.. also should be glob pattern for `testFiles` and `excludedTestFiles` https://docs.cypress.io/guides/references/legacy-configuration#Folders-Files

2022-08-02 20:48 UTC, tianfeng92 approved these changes

2022-08-03 23:13 UTC, merged