New Getting Started content for API Testing
saucelabs/sauce-docs pull request #1388
Opened 2022-08-08 16:25 UTC by lauramthomas

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-08 21:03 UTC, lysannep commented on docs/api-testing.md
> +Use Sauce Connect Proxy to test APIs behind a firewall. This launches a secured tunnel between the Sauce Labs API Testing platform and your APIs. See <a href="/secure-connections/sauce-connect">Sauce
```suggestion
Use Sauce Connect Proxy to test APIs behind a firewall. This launches a secure tunnel between the Sauce Labs API Testing platform and your APIs. See <a href="/secure-connections/sauce-connect">Sauce Connect Proxy</a> for more information.
```

2022-08-08 21:04 UTC, lysannep commented on docs/api-testing.md
> +At its core, Sauce Labs API Testing allows you to use either and HTTP client or a proprietary test composer to generate and edit intelligent contract or functional tests. The tests can be automated w
```suggestion
At its core, Sauce Labs API Testing allows you to use an HTTP client or a proprietary test composer to generate and edit intelligent contract or functional tests. The tests can be automated with any CI/CD tool or using the platform’s scheduler. Functional tests can then be used as load tests or scheduled as uptime monitors.
```

2022-08-08 21:06 UTC, lysannep approved these changes
Looks good to me. Added a couple minor suggestions.

2022-08-09 07:27 UTC, aoleszyn approved these changes
Besides the small typo mentioned by @lysannep , LGTM :)

2022-08-09 08:36 UTC, LoryApiFortress requested changes
The Load testing part is missing:
```suggestion
Load Testing
The platform allows for the creation and execution of load tests using existing functional tests. So once you’ve generated or created a functional test, you can create the load test using these tests.

<a href="/api-testing/load-testing/">Load Testing with API Testing</a>
```

2022-08-09 08:36 UTC, LoryApiFortress commented on docs/api-testing.md
> +Use the API Testing platform to generate contract tests from an OpenAPI specification file. When used with Piestry, our mocking tool, you can test both the consumer and the provider.
```suggestion
Use the API Testing platform to generate contract tests from an OpenAPI specification file. When used with Piestry, our mocking tool, you can test both the consumer and the producer side.
```

2022-08-09 08:36 UTC, LoryApiFortress commented on docs/api-testing.md
> +<a href="/api-testing/import-postman-collection/#importing-a-har-file-from-an-rdc-job">HAR files captured during real device testing</a>
link above is no longer valid, now we have both RDC and VDC. Replace with:
<a href="/api-testing/import-postman-collection/#importing-a-har-file-rdc-and-vdc">Import from HAR file (including HAR files from RDC and VDC)</a>

2022-08-09 08:36 UTC, LoryApiFortress commented on docs/api-testing.md
> +Use Sauce Connect Proxy to test APIs behind a firewall. This launches a secured tunnel between the Sauce Labs API Testing platform and your APIs. See <a href="/secure-connections/sauce-connect">Sauce
```suggestion
Use Sauce Connect Proxy to test APIs behind a firewall. This launches a secure tunnel between the Sauce Labs API Testing platform and your APIs. See <a href="/api-testing/sauce-connect/">Sauce Connect Proxy</a> for more information.
```

2022-08-09 13:26 UTC, lauramthomas commented
@LoryApiFortress Please re-review and approve

2022-08-09 15:19 UTC, LoryApiFortress approved these changes

2022-08-09 16:18 UTC, merged