Added info about allowlisting devices (TCD-2283)
saucelabs/sauce-docs pull request #1428
Opened 2022-08-25 15:22 UTC by lauramthomas

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-25 17:32 UTC, lysannep approved these changes

2022-08-25 17:32 UTC, aoleszyn approved these changes

2022-08-29 15:41 UTC, wswebcreation requested changes
Hi @lauramthomas 

I've added some comments, maybe also check with @kristofmuhi regarding the iCloud and Google accounts to be sure that they are not removed during a cleaning process

2022-08-29 15:41 UTC, wswebcreation commented on docs/mobile-apps/supported-devices.md
> +* Apps installed on the private device can be selected, by name, to be preserved between sessions. These apps and their data will not be cleaned.
```suggestion
* Apps installed on the private device can be selected, by Android `packageName` or iOS `bundleId`, to be preserved between sessions. These apps and their data will not be cleaned.
```

2022-08-29 15:41 UTC, wswebcreation commented on docs/mobile-apps/supported-devices.md
> +* Google accounts signed into the Play Store can be preserved between sessions.
Not sure if this is correct / linked to private devices

2022-08-29 15:41 UTC, wswebcreation commented on docs/mobile-apps/supported-devices.md
> +* Apple IDs signed in to the device and App Store can be preserved between sessions.
Same here, not sure if this is correct / linked to private devices

2022-11-22 21:07 UTC, closed without merging