Add content for Value Drive
saucelabs/sauce-docs pull request #1466
Opened 2022-09-22 14:36 UTC by aliciakrebs

### Description
Add content for Vault Drive

### Motivation and Context
https://saucedev.atlassian.net/browse/TCD-2513

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-22 15:06 UTC, LoryApiFortress reviewed
Apart from the typo, looks good to me!

2022-09-23 17:54 UTC, lauramthomas requested changes

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +description: "The Vault allows you to store variables, code snippets and files that can be used across an entire project."
Add a comma after "code snippets"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +There are two types of API Testing vaults, the **Company Vault** and project-specific **Vault**. While their UI is the same, they serve two different purposes:
Change "and project-specific **Vault**" to "and a project-specific **Vault**"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +The project **Vault**, which you can access from within a project, is where you can store project-specific variables,  test code snippets, and files.<br/><img src={useBaseUrl('img/api-fortress/2021/0
Delete extra space before "test code snippets"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +You should define a variable at the project-specific **Vault** when you need to use the same one across multiple tests. As an example, you could save a password here as a variable and reuse it in mul
Change "You should define" to "Define"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +There are two types of API Testing vaults, the **Company Vault** and project-specific **Vault**. While their UI is the same, they serve two different purposes:
Change the colon to a period.

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +You should define a variable at the project-specific **Vault** when you need to use the same one across multiple tests. As an example, you could save a password here as a variable and reuse it in mul
Change "As an example, you could" to "For example, you can"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  :::tip Import Postman Collections into The Vault
Change "The Vault" to "a Vault"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  Additionally, you can import variables from Postman. See [here](/api-testing/import-postman-collection) for more details.
Change "See [here]" to "See [Importing Postman Collections, Variables, and Environments]"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +If the same variable with the same name definition exists in both the **Projects Vault** and **Company Vault**, then the value in the **Projects Vault** will override the one in the **Company Vault**
Should "Projects Vault" be "project Vault"?

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  While this is a perfectly valid request parameter, it can be hard to manage and update if you scale out your tests. Therefore rather than continuously hard-coding this value into the **Query Params**
Add a comma after "Therefore"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +Here is an example of how it could look like in the project-specific **Vault**:
Change to "The following is an example of how it might look in the project-specific **Vault**"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +Now you can switch the **Query Params** field from **String value** to **Variable** and enter the variable name: `product_id` (see the screenshot below). This way you can have multiple tests in your
Change "This way you can" to "This allows you to"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +In the **Snippets** section of the **Vault**, you can create or import test component/code examples. A _snippet_ is a test code fragment that you can create, import and store in your [Vault](/api-tes
Change "create, import and store" to "create, import, and store"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +Much like with variable scope, snippets saved in a project **Vault** are only available in that project and snippets saved in the **Company Vault** are available across all projects.
Add a comma after "in that project"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +Your changes are saved automagically.
Change "automagically" to "automatically"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  * **Paste Snippet**: allows you to paste the entire component inside the test, allowing you to edit as needed. The pasted components will lose any reference to the original snippet.
Change "allows" to "Allows"; change "allowing you to" to "which you can then"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  * **Invoke Snippet**: creates a **Call** component that will invoke the snippet. If the snippet changes, all the tests containing the Call component to that snippet will inherit the changes.
Change "creates" to "Creates"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
>  A good use case for the snippets feature is building an authentication flow; you don't need nor want to rewrite all authentication steps for every single test. Instead, call the snippet that contains
Change "you don't need nor want" to "you don't need"

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +In the **Drive** section of a project-specific **Vault**, you can upload files to use in your tests.The file size limit for an indivudal file is 16 MB. The total limit for the **Company Vault** is 10
Add a space after "to use in your tests."

2022-09-23 17:54 UTC, lauramthomas commented on docs/api-testing/vault.md
> +In the **Drive** section of a project-specific **Vault**, you can upload files to use in your tests.The file size limit for an indivudal file is 16 MB. The total limit for the **Company Vault** is 10
Change "indivudal" to "individual"

2022-09-27 16:54 UTC, merged