[DEVX-1941] Add docs for playwright-cucumber
saucelabs/sauce-docs pull request #1483
Opened 2022-10-06 00:00 UTC by tianfeng92

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-06 00:07 UTC, alexplischke commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +title: Configuring Your Playwright with Cucumber Tests
I think we should change the general wording to `Cucumber Tests with Playwright`.
A benign change, but main focus are the Cucumber tests, with playwright as the automation framework underneath.

Also worth mentioning somewhere that this is CucumberJs, specifically.

2022-10-06 19:56 UTC, alexplischke commented on docs/web-apps/automated-testing/_partials/_advanced-cucumber-playwright.md
> +`saucectl` provides a way to run Cucumber-js test with Playwright. In this case, Cucumber-js is running as the test runner and using Playwright as the test framework. You need to specified Cucumber-j
```suggestion
`saucectl` provides a way to run Cucumber.js tests with Playwright. In this case, Cucumber.js acts as the test framework, utilizing Playwright as the automation framework. This setup requires a dedicated Cucumber.js + Playwright [configuration](/web-apps/automated-testing/playwright/cucumber).
```

2022-10-06 21:39 UTC, aliciakrebs requested changes

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/_partials/_advanced-cucumber-playwright.md
> +`saucectl` provides a way to run Cucumber-js test with Playwright. In this case, Cucumber-js is running as the test runner and using Playwright as the test framework. You need to specified Cucumber-j
```suggestion
`saucectl` provides a way to run Cucumber-js tests with Playwright. In this case, Cucumber-js is running as the test runner and using Playwright as the test framework. To run Cucumber-js tests with Playwright you'll need to specify the [Cucumber-js related configurations](/web-apps/automated-testing/playwright/cucumber).
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Options to be provided to formatters. You can check more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md).
```suggestion
Options to provide to formatters. See the [Cucumber-js Formatters documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md) for more information. 
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Name/path and (optionally) output file path of each formatter to use. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md).
```suggestion
Name/path and (optionally) output file path of each formatter to use. See the [Cucumber-js Formatters documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md) for more information.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Tag expression to filter which Cucumber scenarios should be run. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/filtering.md#tags).
```suggestion
Tag expression to filter which Cucumber scenarios run. See the [Cucumber-js Filtering documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/filtering.md#tags) for more information.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Paths to where your support code is, for ESM. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/esm.md).
```suggestion
Paths to your support code for ESM. See the [Cucumber-js ES Modules (experimental) documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/esm.md) for more information. 
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Paths to where your support code is, for CommonJS. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-code).
```suggestion
Paths to your support code for CommonJS. See the [Cucumber-js Configuration documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-code) for more information.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Shows the full backtrace for errors.
```suggestion
Specifies whether to show the full backtrace for errors.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Paths to where the feature files are, using glob pattern. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-features).
```suggestion
Paths to feature files. See the [Cucumber-js Configuration documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-features) for more information. You can use glob pattern to indicate all files that match a specific value, such as a file name, type, or directory.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Instructs `saucectl` run tests remotely through Sauce Labs (`sauce`) or locally on `docker`. You can override this setting for individual suites using the `mode` setting within the [`suites`](#suites
```suggestion
Instructs `saucectl` to run tests remotely through Sauce Labs (`sauce`) or locally on `docker`. You can override this setting for individual suites using the `mode` setting within the [`suites`](#suites) object. If not set, the default value is `sauce`.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +In order to run Cucumber-js with Playwright test, you need to install the following required packages locally and then add dependencies to the config.
```suggestion
In order to run Cucumber-js tests Playwright, you must to install the following required packages locally, and then add the dependencies to the configuration file.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Regular expressions of which Cucumber scenario names should match one of to be run. See more details [here](https://github.com/cucumber/cucumber-js/blob/main/docs/filtering.md#names).
```suggestion
Specifies with regular expression matching which Cucumber scenarios to run. See the [Cucumber-js Filtering documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/filtering.md#names) for more information.
```

2022-10-06 21:39 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +`saucectl` doesn't support the way to run Cucumber-Playwright test via installing Cucumber-js related packages on the fly.
```suggestion
`saucectl` doesn't support running Playwright-Cucumber tests via installing Cucumber related packages on the fly.
```

2022-10-07 14:25 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +`saucectl` doesn't support running Playwright-Cucumber tests via installing Cucumber related packages on the fly.
```suggestion
`saucectl` doesn't support running Cucumber-js tests with Playwright via installing Cucumber related packages on the fly.
```

2022-10-07 14:28 UTC, aliciakrebs commented on docs/web-apps/automated-testing/_partials/_advanced-cucumber-playwright.md
> +`saucectl` provides a way to run Cucumber.js tests with Playwright. In this case, Cucumber.js acts as the test framework, utilizing Playwright as the automation framework. This setup requires a dedic
```suggestion
`saucectl` provides a way to run Cucumber.js tests with Playwright. In this case, Cucumber.js acts as the test framework, utilizing Playwright as the automation framework. Running Cucumber-js tests with Playwright requires a dedicated  [configuration](/web-apps/automated-testing/playwright/cucumber).
```

2022-10-07 14:45 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +In order to run Cucumber-js tests Playwright, you must to install the following required packages locally, and then add the dependencies to the configuration file.
```suggestion
In order to run Cucumber-js tests with Playwright, you must to install the following required packages locally, and then add the dependencies to the configuration file.
```

2022-10-07 14:52 UTC, aliciakrebs requested changes

2022-10-07 14:52 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright/cucumber.md
> +Launching the browser for Cucumber-Playwright test should be done on customer's side. Hence `saucectl` cannot guarantee the displayed browser name is matched with the actual browser name.
```suggestion
Launching the browser for Cucumber.js Playwright tests should be done on customer's side. Hence `saucectl` cannot guarantee the displayed browser name is matched with the actual browser name.
```

2022-10-07 16:41 UTC, lysannep approved these changes

2022-10-07 20:21 UTC, aliciakrebs approved these changes

2022-10-07 20:21 UTC, merged