[IAM-4740] add docs for the new SSO
saucelabs/sauce-docs pull request #1716
Opened 2023-02-09 12:09 UTC by przemek-sl

### Description, Motivation and Context
We are going to release the new SSO implementation. Any new SSO integration is going to be set up using the new flow. I'm adding the documentation for the new SSO ([second commit](https://github.com/saucelabs/sauce-docs/commit/e7a5f9b277a052f4ab324c9175294aca95e07a38)). 

However, we have to keep the existing docs for customers who still use the old SSO, until they migrate to the new SSO. That is why I marked the existing SSO docs as deprecated ([first commit](https://github.com/saucelabs/sauce-docs/commit/7835206eb48b69ebb17a2bc8f39731bee641f02e)).

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist
- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-09 18:17 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +   - Follow the instructions from your IdP to provide the Sauce Labs SAML metadata obtained in step 1. If your IdP does not allow uploading SP metadata, set up the integration manually using the info
Add a link to the heading for this "in the paragraphs below" 

```suggestion
   - Follow the instructions from your IdP to provide the Sauce Labs SAML metadata obtained in step 1. If your IdP does not allow uploading service provider  metadata, set up the integration manually using the information provided in the paragraphs below.
```

2023-02-09 18:18 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +Here is the list of settings which are required by Sauce Labs Service Provider:
```suggestion
Here is the list of settings that are required by Sauce Labs Service Provider:
```

2023-02-09 18:21 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +Either SAML Assertion or SAML response **must be signed**.
```suggestion
Either the SAML Assertion or SAML Response **must be signed**.
```

2023-02-09 18:22 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +Encryption of SAML assertion **is not mandatory**.
```suggestion
Encryption of the SAML Assertion **is not mandatory**.
```

2023-02-09 18:23 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +If you start to see errors after enabling encryption, make sure that you use the encryption certificate which is advertised in Sauce Labs metadata (in the tag `<KeyDescriptor use="encryption">`) and
```suggestion
If you start to see errors after enabling encryption, make sure that you use the encryption certificate that is advertised in Sauce Labs metadata (in the tag `<KeyDescriptor use="encryption">`) and the encryption algorithm matches the algorithm provided in Sauce Labs metadata (value of the attribute `Algorithm` in the tag `EncryptionMethod`).
```

2023-02-09 19:13 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +The value of the attribute NameID in SAML Response must be also **a valid email address**. We do not accept values which are not email addresses, for instance usernames, IDs, etc.
```suggestion
The value of the attribute NameID in SAML Response must be **a valid email address**. We do not accept values which are not email addresses, for instance usernames, IDs, etc.
```

2023-02-09 19:14 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +Sauce Labs Service Provider does not require to include any extra attributes in SAML Response.
```suggestion
Sauce Labs Service Provider does not require any extra attributes in the SAML Response.
```

2023-02-09 19:17 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +This section is relevant only for identity providers which enabled encryption of SAML assertions.
```suggestion
This section is relevant only for identity providers that enabled encryption of SAML Assertions.
```

2023-02-09 19:19 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +If you enabled encryption of SAML assertions in your IdP, it means that you uploaded the certificate which is served in Sauce Labs [metadata](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2
```suggestion
If you enabled encryption of SAML Assertions in your IdP,  you must upload the certificate that is provided in Sauce Labs [metadata](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2F%2Faccounts.saucelabs.com%2Fsp).
```

2023-02-09 19:20 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +The certificate is valid one year. **120 days** before the expiration date the new certificate will appear in Sauce Labs [metadata](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2F%2Faccoun
```suggestion
The certificate is valid for one year. **120 days** before the expiration date the new certificate will be available in Sauce Labs [metadata](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2F%2Faccounts.saucelabs.com%2Fsp). Upload the new certificate in your IdP.
```

2023-02-09 19:33 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +1. On Sauce Labs, click **Account** and then click **Team Management**.
```suggestion
1. On Sauce Labs, click **Account**,  and then click **Team Management**.
```

2023-02-09 19:37 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +5. Under **Status** section, toggle the switch to **Enabled**. For more information about adding new users and SSO considerations, see [Adding and Deactivating Users](/basics/acct-team-mgmt/adding-de
```suggestion
5. In the **Status** section, toggle the switch to **Enabled**. For more information about adding new users and SSO considerations, see [Adding and Deactivating Users](/basics/acct-team-mgmt/adding-deactivating-users).
```

2023-02-09 19:40 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +We strongly recommend to assign your company email domains to your Sauce Labs organization. It will allow users who do not have account at Sauce Labs to initiate SSO at [the Sauce Labs login page](ht
```suggestion
We strongly recommend that you  assign your company email domains to your Sauce Labs organization. This allows users who do not have an account at Sauce Labs to initiate SSO at [the Sauce Labs login page](https://accounts.saucelabs.com).
```

2023-02-09 19:42 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +## Not supported features
```suggestion
##  Unsupported features
```

2023-02-09 19:42 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +- integration with multiple identity provider in a single Sauce Labs organization
```suggestion
- integration with multiple identity providers in a single Sauce Labs organization
```

2023-02-09 19:48 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +2. Click the button **`SSO`**.
```suggestion
2. Click **SSO**.
```

2023-02-09 19:49 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +3. Input your company email address and click **`Log in`**.
```suggestion
3. Enter your email address and click **Log in**.
```

2023-02-09 19:49 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +4. You will be redirected to your identity provider in order to authenticate with your company credentials.
```suggestion
4. You will be redirected to your identity provider to authenticate with your company credentials.
```

2023-02-09 19:50 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +5. If you are already authenticated at your identity provider, you will be redirected to Sauce Labs dashboard.
```suggestion
5. If you are already authenticated at your identity provider, you will be redirected to the Sauce Labs dashboard.
```

2023-02-09 19:52 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +If new users are not able to log in via SP-initiated flow, most probably your company email domains were not assigned to your organization. Check [here](/basics/sso/setting-up-sso#email-domains) how
```suggestion
If new users are not able to log in via the SP-initiated flow, make sure that  your [company email domains were assigned to your organization](/basics/sso/setting-up-sso#email-domains).
```

2023-02-09 19:53 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +If you paste a link to for example a test results page at Sauce Labs and you are not authenticated. You will be redirected to the Sauce Labs login page.
```suggestion
If you paste a link to, for example,  a test results page at Sauce Labs and you are not authenticated. You will be redirected to the Sauce Labs login page.
```

2023-02-09 19:55 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +   - Click the button **`SSO`**.
```suggestion
   - Click **SSO**.
```

2023-02-09 19:55 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +   - Input your company email address.
```suggestion
   - Enter your company email address.
```

2023-02-09 19:55 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +   - Click the button **`Log in`**.
```suggestion
   - Click **Log in**.
```

2023-02-09 19:59 UTC, aliciakrebs commented on docs/basics/sso/logging-in-via-sso.md
> +2. Click on **`Sauce Labs`** tile in your applications catalogue.
```suggestion
2. Click the **Sauce Labs** tile in your applications catalog.
```

2023-02-09 20:02 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +you set it up. Unlike to the [old SSO implementation](/basics/sso-deprecated/setting-up-single-sign-on) which is already deprecated.
```suggestion
you set it up. Unlike to the [old SSO implementation](/basics/sso-deprecated/setting-up-single-sign-on), which has been deprecated.
```

2023-02-09 20:06 UTC, aliciakrebs commented on docs/basics/sso/setting-up-sso.md
> +1. Obtain SAML metadata from Sauce Labs Service Provider which is served under [this link](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2F%2Faccounts.saucelabs.com%2Fsp).
```suggestion
1. Obtain SAML metadata from Sauce Labs Service Provider, which is served under [this link](https://accounts.saucelabs.com/am/sso/metadata/https%3A%2F%2Faccounts.saucelabs.com%2Fsp).
```

2023-02-09 20:08 UTC, aliciakrebs requested changes
I made some copy edits.

2023-02-10 11:06 UTC, przemek-sl commented
@aliciakrebs I pushed fixes for all your comments.

2023-02-10 17:12 UTC, aliciakrebs approved these changes

2023-02-27 12:38 UTC, merged