Biometric Authentication update
saucelabs/sauce-docs pull request #1769
Opened 2023-03-02 18:12 UTC by aoleszyn

Biometric Authentication update

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

2023-03-02 18:56 UTC, lysannep approved these changes

2023-03-02 19:18 UTC, wswebcreation commented on docs/mobile-apps/features/biometric-authentication.md
> +With Sauce Labs Biometric Authentication, you can simulate biometric authentication events within your app during automated testing. This feature allows you to test the app's ability to recognize and
```suggestion
With Sauce Labs Biometric Authentication, you can simulate biometric authentication events within your app during live and automated testing. This feature allows you to test the app's ability to recognize and respond to biometric events, without physically testing it on a device. Biometric Authentication refers to the use of physical characteristics, such as fingerprint (Touch ID) or facial recognition (Face ID) to verify the user's identity.
```

2023-03-02 19:18 UTC, wswebcreation requested changes
Added a comment

2023-03-03 06:29 UTC, wswebcreation commented on docs/mobile-apps/features/biometric-authentication.md
> +:::note
Shouldn't this be a caution? To emphasis this more?

2023-03-03 09:34 UTC, aoleszyn commented on docs/mobile-apps/features/biometric-authentication.md
> +:::note
```suggestion
:::caution
```

2023-03-03 09:41 UTC, wswebcreation approved these changes
LGTM

2023-03-03 09:49 UTC, merged