Adds  quickstarts for Orchestrate.
saucelabs/sauce-docs pull request #1978
Opened 2023-05-08 17:55 UTC by aliciakrebs

### Description
Adds  quickstarts for Orchestrate. 

### Motivation and Context
[devx-2291](https://saucedev.atlassian.net/browse/DEVX-2291).

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-08 18:30 UTC, aliciakrebs commented on docs/orchestrate/quickstart-playwright.md
> +Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started/#how-it-works) fo
```suggestion
Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started.md#how-it-works) for more details.
```

2023-05-08 18:31 UTC, aliciakrebs commented on docs/orchestrate/quickstart-webdriverio.md
> +Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started/#how-it-works) fo
```suggestion
Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started.md#how-it-works) for more details.
```

2023-05-08 19:54 UTC, alexplischke approved these changes

2023-05-10 18:52 UTC, lysannep commented on docs/web-apps/automated-testing/playwright.md
> +- [Run your tests in Orchestrate](/docs/orchestrate/quickstart-playwright.md): Use `saucectl` to run tests with a containerized test runner.
```suggestion
- [Run your tests in Orchestrate](/docs/orchestrate/quickstart-playwright): Use `saucectl` to run tests with a containerized test runner.
```

2023-05-10 19:50 UTC, lysannep commented on docs/orchestrate/quickstart-playwright.md
> +Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started.md#how-it-works)
```suggestion
Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See [How it Works](/docs/orchestrate/getting-started.md#how-it-works) for more details.
```

2023-05-10 19:53 UTC, lysannep commented on docs/orchestrate/quickstart-playwright.md
> +This page explains how to run your [Playwright](/docs/web-apps/automated-testing/playwright.md) tests in Sauce Orchestrate with `saucectl`.
```suggestion
This page explains how to run your [Playwright](/docs/web-apps/automated-testing/playwright) tests in Sauce Orchestrate with `saucectl`.
```

2023-05-10 19:54 UTC, lysannep commented on docs/orchestrate/quickstart-playwright.md
> +The following example uses a project with a `saucectl` configuration file that is set up to run in Orchestrate. See [`saucectl` Configuration](/docs/orchestrate/saucectl-configuration.md) for more in
```suggestion
The following example uses a project with a `saucectl` configuration file that is set up to run in Orchestrate. See [`saucectl` Configuration](/docs/orchestrate/saucectl-configuration.md) for more information about the configuration and run options available. The example also has a Dockerfile for building the container image. See [Building Images](/docs/orchestrate/building-images) for more information about creating your own container images.
```

2023-05-10 19:57 UTC, lysannep commented on docs/orchestrate/quickstart-webdriverio.md
> +Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started.md#how-it-works)
```suggestion
Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See [How it Works](/docs/orchestrate/getting-started/#how-it-works) for more details.
```

2023-05-10 19:57 UTC, lysannep commented on docs/orchestrate/quickstart-webdriverio.md
> +Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See the [Getting Started > How it Works section](/docs/orchestrate/getting-started.md#how-it-works)
```suggestion
Sauce Orchestrate uses container technology to package and run your tests in the Sauce Labs cloud. See [How it Works](/docs/orchestrate/getting-started/#how-it-works) for more details.
```

2023-05-10 19:57 UTC, lysannep commented on docs/orchestrate/quickstart-webdriverio.md
> +The following example uses a project with a `saucectl` configuration file that is set up to run in Orchestrate. See [`saucectl` Configuration](/docs/orchestrate/saucectl-configuration.md) for more in
```suggestion
The following example uses a project with a `saucectl` configuration file that is set up to run in Orchestrate. See [`saucectl` Configuration](/docs/orchestrate/saucectl-configuration) for more information about the configuration and run options available. The example also has a Dockerfile for building the container image. See [Building Images](/docs/orchestrate/building-images) for more information about creating your own container images.
```

2023-05-10 20:00 UTC, lysannep commented on docs/orchestrate/quickstart-webdriverio.md
> +`saucectl` detects your Sauce Labs credentials [environment variables](/basics/environment-variables) and prioritizes them over values in the `credentials.yml` file when both are present. **If you ha
```suggestion
`saucectl` uses your Sauce Labs credentials as [environment variables](/basics/environment-variables) and prioritizes them over values in the `credentials.yml` file when both are present. **If you have set them, you may skip this step.** Not sure if you have them set? Run the following command to check:
```

2023-05-10 20:01 UTC, lysannep requested changes

2023-05-10 20:01 UTC, lysannep commented on docs/orchestrate/quickstart-playwright.md
> +`saucectl` detects your Sauce Labs credentials [environment variables](/basics/environment-variables) and prioritizes them over values in the `credentials.yml` file when both are present. **If you ha
```suggestion
`saucectl` uses your Sauce Labs credentials as [environment variables](/basics/environment-variables) and prioritizes them over values in the `credentials.yml` file when both are present. **If you have set them, you may skip this step.** Not sure if you have them set? Run the following command to check:
```

2023-05-10 20:34 UTC, lysannep approved these changes

2023-05-10 20:41 UTC, lysannep commented on docs/orchestrate/quickstart-playwright.md
> +id: playwright-orchestrate-quickstart
```suggestion
id: quickstart-webdriverio
```

2023-05-10 20:42 UTC, lysannep commented on docs/orchestrate/quickstart-webdriverio.md
> +id: webdriverio-orchestrate-quickstart
```suggestion
id: quickstart-webdriverio
```

2023-05-10 20:43 UTC, lysannep commented on sidebars.js
> +                'orchestrate/webdriverio-orchestrate-quickstart',
```suggestion
                'orchestrate/quickstart-webdriverio',
```

2023-05-10 20:43 UTC, lysannep commented on sidebars.js
> +                'orchestrate/webdriverio-orchestrate-quickstart',
```suggestion
                'orchestrate/quickstart-webdriverio',
```

2023-05-10 20:44 UTC, lysannep commented on sidebars.js
> +                'orchestrate/playwright-orchestrate-quickstart',
```suggestion
                'orchestrate/quickstart-playwright,
```

2023-05-10 20:49 UTC, aliciakrebs commented on docs/web-apps/automated-testing/playwright.md
> +- [Run your tests in Orchestrate](/orchestrate/playwright-orchestrate-quickstart): Use `saucectl` to run tests with a containerized test runner.
```suggestion
- [Run your tests in Orchestrate](/orchestrate/quickstart-playwright): Use `saucectl` to run tests with a containerized test runner.
```

2023-05-10 20:58 UTC, aliciakrebs commented on docs/orchestrate/quickstart-playwright.md
> +This page explains how to run your [Playwright](/docs/web-apps/automated-testing/playwright) tests in Sauce Orchestrate with `saucectl`.
```suggestion
This page explains how to run your [Playwright](/web-apps/automated-testing/playwright) tests in Sauce Orchestrate with `saucectl`.
```

2023-05-11 15:32 UTC, merged