Update instant-booted-simulators.md
saucelabs/sauce-docs pull request #2088
Opened 2023-06-07 20:59 UTC by eyaly

Since this is a code example, Yell (A customer) copied/pasted this line of code to their framework as it is and got an error to creating the driver

### Description

### Motivation and Context

### Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

2023-06-07 22:42 UTC, lysannep approved these changes
@eyaly Thank you!

2023-06-08 05:07 UTC, wswebcreation requested changes
Can you change all values, you now only changed one for JAVA, but we have all languages in here

2023-06-08 09:46 UTC, eyaly commented on docs/mobile-apps/features/instant-booted-simulators.md
> +// Possible values: "latest", "current_major", "previous_major"
Thanks @wswebcreation. I didn't even make the change for Java iPad... So now I added the change for all

2023-06-08 10:08 UTC, wswebcreation requested changes
Small improvements, you can accept them and then we can merge it.

Thanks

2023-06-08 10:43 UTC, wswebcreation approved these changes

2023-06-08 11:20 UTC, merged