removing v1 endpoints
saucelabs/sauce-docs pull request #2317
Opened 2023-07-25 13:55 UTC by LoryApiFortress

### Description

### Motivation and Context

### Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

2023-07-25 13:58 UTC, LoryApiFortress commented
@thehannahm according to @paweldudzinski message (https://saucelabs.slack.com/archives/CBQ3FG347/p1690292466156369?thread_ts=1690289897.738759&cid=CBQ3FG347) I've remove all the v1/analytics endpoints. Let me know if I can go ahead or if I should disregard the change. Thanks

2023-07-25 17:52 UTC, aoleszyn approved these changes

2023-07-26 01:10 UTC, thehannahm requested changes
@LoryApiFortress, my understanding is that it's best practice to run things like this through a formal end of life process, where we announce when the documentation will be removed. As far as I know, we still have the majority of our customers using v1, and we should at least give them time to prepare for this change. We can discuss this with @paweldudzinski.

2023-07-26 07:36 UTC, LoryApiFortress commented
> @LoryApiFortress, my understanding is that it's best practice to run things like this through a formal end of life process, where we announce when the documentation will be removed. As far as I know, we still have the majority of our customers using v1, and we should at least give them time to prepare for this change. We can discuss this with @paweldudzinski.

@thehannahm ok, I'll close this PR for now, I'll remove the endpoints after a formal EOL announcement.

2023-07-26 07:36 UTC, closed without merging