Update usage for Private devices
saucelabs/sauce-docs pull request #2786
Opened 2024-05-28 16:29 UTC by adam-saucelabs

### Description
Updating usage.md for private device usage that we are launching this week 

### Motivation and Context

### Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

2024-05-28 20:53 UTC, CharlieBurnett requested changes
Almost perfect, just fix some typoes and formatting

2024-05-28 20:53 UTC, CharlieBurnett commented on docs/insights/usage-report.md
> +With Suace Labs Real Device usage analytics your organization can get a view of both Public device concurrency usage as well as Private device usage to get the most of your Sauce Labs testing strateg
Spell our company name correctly plz

2024-05-28 20:53 UTC, CharlieBurnett commented on docs/insights/usage-report.md
>  <img src={useBaseUrl('img/insights/ccy-org-month-rdc-public.png')} alt="Public Real Device concurrency usage at organization level"/>
nit: why is Per Month not capitalized in the title but all other words are

2024-05-28 20:57 UTC, adam-saucelabs commented on docs/insights/usage-report.md
> +With Suace Labs Real Device usage analytics your organization can get a view of both Public device concurrency usage as well as Private device usage to get the most of your Sauce Labs testing strateg
fixed

2024-05-29 15:44 UTC, CharlieBurnett approved these changes

2024-05-29 15:45 UTC, merged