Added network capture docs for live testing
saucelabs/sauce-docs pull request #2895
Opened 2024-08-20 15:41 UTC by diegoperini

### Description
Added network capture logs for testing sessions.

### Types of Changes
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation fix (typos, incorrect content, missing content, etc.)

2024-08-20 16:46 UTC, kristofmuhi requested changes

2024-08-21 08:53 UTC, diegoperini commented on docs/mobile-apps/features/network-capture.md
> +Now you can start your live or automated testing session. Your network logs will be captured and displayed in the test results page as well as inside the live testing window.
Thank you, applied.

2024-08-21 08:53 UTC, diegoperini commented on docs/mobile-apps/features/network-capture.md
> +1. Enable network capture for your app like described above. You can skip this step for cross browser testing.
Makes sense. Removed.

2024-08-21 10:41 UTC, kristofmuhi approved these changes

2024-08-21 16:29 UTC, kristofmuhi approved these changes

2024-08-21 16:29 UTC, merged