Add description for espresso testOptions object
saucelabs/sauce-docs pull request #345
Opened 2021-04-28 23:58 UTC by valentyn88

**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-04-29 17:06 UTC, sweeneyskirt-sl requested changes
I have made a few suggestions for clarity. @vrunoa -- Valentyn says you are the Android expert. Would you mind taking a look to make sure the descriptions are clear and "androidy"? ;)

2021-04-29 17:06 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/espresso.md
> +__Description__: Field for defining filter by selected annotation.
```suggestion
__Description__: Instructs `saucectl` to run only tests that match a custom annotation that you have set. 
```

2021-04-29 21:45 UTC, valentyn88 commented on docs/testrunner-toolkit/configuration/espresso.md
> +annotation.
done

2021-04-29 21:46 UTC, valentyn88 commented on docs/testrunner-toolkit/configuration/espresso.md
> +__Description__: Field for defining filter by specific test size.
done

2021-04-29 21:46 UTC, valentyn88 commented on docs/testrunner-toolkit/configuration/espresso.md
> +__Description__: Field for defining filter by selected classes.
done

2021-04-29 21:46 UTC, valentyn88 commented on docs/testrunner-toolkit/configuration/espresso.md
> +__Description__: Field for defining filter by selected package.
done

2021-04-29 21:46 UTC, valentyn88 commented on docs/testrunner-toolkit/configuration/espresso.md
> +__Description__: Field for defining filter by selected annotation.
done

2021-04-30 00:19 UTC, sweeneyskirt-sl approved these changes

2021-04-30 12:50 UTC, merged