Add strictSSL field for npm
saucelabs/sauce-docs pull request #349
Opened 2021-04-29 22:54 UTC by tianfeng92

**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-04-30 00:24 UTC, sweeneyskirt-sl approved these changes

2021-04-30 12:57 UTC, sweeneyskirt-sl commented
Hi @tianfeng92  -- This PR has `draft` status. Are you leaving it open for now to apply more changes, or is it ready to merge?

2021-05-04 18:05 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/common-syntax.md
> +__Description__: Whether or not to do SSL key validation when making requests to the registry via https. If this value is not set, npm will set it to `true` by default.
```suggestion
__Description__: Instructs npm to perform SSL key validation when making requests to the registry via https (`true`) or not (`false`). Defaults to `true` when not set.
```

2021-05-04 18:06 UTC, sweeneyskirt-sl requested changes
One suggestion to make it clear which value corresponds to which behavior. Thanks!

2021-05-04 20:22 UTC, tianfeng92 commented on docs/testrunner-toolkit/configuration/common-syntax.md
> +__Description__: Whether or not to do SSL key validation when making requests to the registry via https. If this value is not set, npm will set it to `true` by default.
Thanks!

2021-05-04 20:28 UTC, sweeneyskirt-sl approved these changes

2021-05-04 20:36 UTC, merged