Tcd 1539
saucelabs/sauce-docs pull request #403
Opened 2021-05-25 22:50 UTC by spider-sauce

### Description

Documentation refactor based on [slack thread](https://saucelabs.slack.com/archives/G01L52RRAVD/p1621315598005000)
JIRA Issue:[TCD-1539]( https://saucedev.atlassian.net/browse/TCD-1539)
### Motivation and Context

Previous doc only detailed how to run a script against Sauce Labs rather than cover a more detailed approach with:
* How to set up / plug in the `axe-core` library and work with the accessibility feature
* How to enable the Integration in Sauce Labs UI - TODO
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-27 19:02 UTC, lroslonek requested changes

2021-05-27 20:39 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +}
That's fair. So If I'm to remove the config object, should I remove all mention of `wdio` and only use psuedocode/code snippets to keep it framework agnostic?

2021-05-27 20:41 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +"@axe-core/webdriverio": "4.1.2-alpha.106"
same thing here ☝️ , should I only reference the general `axe-core` [npm package](https://www.npmjs.com/package/axe-core) and maybe provide links to the specific bindings?

2021-05-27 20:41 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +In order to test on multiple different browsers and platforms, add the configuration options in the `capabilities` object.
If we remove the mention of `wdio` would it still make sense to cover `chromedriver` and the like? If not, should we remove this section too?

2021-05-27 23:23 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +}
Removed and now I link to the wdio docs.

2021-05-27 23:24 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +"@axe-core/webdriverio": "4.1.2-alpha.106"
Fixed

2021-05-27 23:25 UTC, spider-sauce commented on docs/basics/integrations/deque.md
> +In order to test on multiple different browsers and platforms, add the configuration options in the `capabilities` object.
Added a section for using local drivers, is there anything else needed for axe to work with the driver objects?

2021-05-28 08:42 UTC, lroslonek commented on docs/basics/integrations/deque.md
> +}
it's not really framework agnostic, but it's framework's configuration agnostic. Other places where you mention `wdio` are ok, but this one is a specific configuration, which is not required to run accessibility test

2021-05-28 08:45 UTC, lroslonek commented on docs/basics/integrations/deque.md
> +"@axe-core/webdriverio": "4.1.2-alpha.106"
I think I was wrong with this one. I noticed that Deque is also referring to the alpha channel in their docs (https://www.deque.com/saucelabs/get-started/), thus I think we should also. Sorry!

2021-05-28 08:58 UTC, lroslonek commented on docs/basics/integrations/deque.md
> +In order to test on multiple different browsers and platforms, add the configuration options in the `capabilities` object.
no, I guess it's ok right now

2021-06-01 16:36 UTC, spider-sauce commented
@lroslonek I fixed the suggested changes. If it's ok with you I'm going to merge this so we can replace the current customer-facing doc with this one. If there's further changes/need for further iteration we can create a new ticket.

2021-06-01 16:37 UTC, merged