Add xcuitest doc
saucelabs/sauce-docs pull request #415
Opened 2021-06-01 00:07 UTC by tianfeng92

**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-01 07:16 UTC, FriggaHel requested changes

2021-06-01 07:16 UTC, FriggaHel commented on docs/testrunner-toolkit.md
>        {"label":"Espresso","value":"espresso"}
```suggestion
      {"label":"Espresso","value":"espresso"},
```

2021-06-01 07:16 UTC, FriggaHel commented on docs/testrunner-toolkit/configuration/xcuitest.md
> +xcuit:
```suggestion
xcuitest:
```

2021-06-01 13:40 UTC, sweeneyskirt-sl approved these changes
This looks fine to me, but I noticed there is no simulators property (like Espresso's emulators). Is it not yet supported for XCUITest?

2021-06-01 15:49 UTC, tianfeng92 commented on docs/testrunner-toolkit/configuration/xcuitest.md
> +xcuit:
updated

2021-06-01 15:51 UTC, tianfeng92 commented
@sweeneyskirt-sl `simulators` hasn't been implemented yet. So currently there is no documented field.

2021-06-02 15:44 UTC, FriggaHel approved these changes

2021-06-02 16:01 UTC, merged