Deprecate saucectl new
saucelabs/sauce-docs pull request #418
Opened 2021-06-01 16:56 UTC by alexplischke

### Description
Remove any mention of `saucectl new`. Since we don't have a true bootstrapping mechanism yet (and `saucectl new` never was), instances of `saucectl new` were replaced by references to the example repos instead.

2021-06-01 17:26 UTC, mhan83 approved these changes
Changes look good. Though I wonder, if in the absence of a true bootstrapping option with `saucectl`, whether we want to have explicit instructions for getting `saucectl` working with existing projects. Maybe that belongs in the individual example repos though?

2021-06-01 17:31 UTC, FriggaHel commented on docs/web-apps/automated-testing/playwright.md
> +You can run a working Cypress sample test in under ten minutes!
```suggestion
You can run a working Playwright sample test in under ten minutes!
```

2021-06-01 17:31 UTC, FriggaHel commented on docs/web-apps/automated-testing/playwright.md
> +Begin by installing the `saucectl` CLI in the root directory of your existing Cypress project or your intended directory.
```suggestion
Begin by installing the `saucectl` CLI in the root directory of your existing Playwright project or your intended directory.
```

2021-06-01 17:58 UTC, FriggaHel approved these changes

2021-06-01 18:17 UTC, sweeneyskirt-sl approved these changes

2021-06-01 19:19 UTC, sweeneyskirt-sl requested changes
Hey @alexplischke -- could you please leave this js-quickstart in for now? Lindsay is edit it to remove references to `saucectl new` and point to the demo repos, but it is linked in the UI, so we don't want to break it just yet.

2021-06-02 14:29 UTC, sweeneyskirt-sl requested changes

2021-06-02 14:29 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration.md
> +The `.sauceignore` allows you to designate certain files to be excluded from bundling.
```suggestion
The `.sauceignore` file allows you to designate certain files to be excluded from bundling.
```

2021-06-02 14:31 UTC, sweeneyskirt-sl approved these changes
Made one small wording correction and committed it. Also pulled from master so this branch is in sync. As soon as the CI tests finish, you should be good to go.

2021-06-02 15:45 UTC, merged