[DEVX-956] Add reporters documentation for cypress
saucelabs/sauce-docs pull request #591
Opened 2021-08-06 21:49 UTC by FriggaHel

**Thank you for contributing to the `sauce-docs` project!**
**A well described pull request helps maintainers quickly review and merge your change**

Before submitting your PR, please check our [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD)
guidelines, applied for this repository. Avoid large PRs, help reviewers by making them as simple 
and short as possible.

### Description

Add references to cypress `reporters` field.

Should not be merged before the new release au `sauce-cypress-runner` and `saucectl` is made !

### Motivation and Context

New feature.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [x] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-06 22:00 UTC, alexplischke commented on docs/testrunner-toolkit/configuration/cypress.md
> +Reporter options are specific for each reporter. Take a look to your reporter options in order to know which options are available.
```suggestion
Reporter options are specific for each reporter. Consult your reporter documentation, in order to know which options are available.
```

2021-08-09 17:08 UTC, sweeneyskirt-sl requested changes

2021-08-09 17:08 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/cypress.md
> +The name of the reporter to enable.
```suggestion
The name of the reporter to enable, which corresponds to the `reporter` property in the `cypres.json` file.
```

2021-08-09 17:08 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/cypress.md
> +:::
```suggestion
:::note
Some reporters may require you to install dependencies.
:::
```

2021-08-09 17:08 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/cypress.md
> +The options of reporters you want to add.
```suggestion
Any relevant settings that are be supported by the specified reporter. These properties correspond to the `reporterOptions` object in the `cypress.json` file.
```

2021-08-09 17:08 UTC, sweeneyskirt-sl commented on docs/testrunner-toolkit/configuration/cypress.md
> +:::
```suggestion
```

2021-08-09 17:09 UTC, sweeneyskirt-sl commented
Hey @alexplischke -- I made a couple edits. Hoping you will give a second scan before we merge. 🙏

2021-08-10 18:26 UTC, merged