Fixing Links from Clara's Scanner
saucelabs/sauce-docs pull request #599
Opened 2021-08-12 23:13 UTC by sweeneyskirt-sl

### Description
Fixed a lot of links that either pointed to the wiki or were broken due to a missing front `/`.

### Motivation and Context
@claramyko created a scan that identifies our broken links and links that point to the wiki.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [X] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-12 23:34 UTC, spider-sauce requested changes
minor changes, see my suggested commits.

2021-08-12 23:34 UTC, spider-sauce commented on docs/dev/glossary.md
> +A mobile software app written in a programming language specific to the platform it is being developed for: either iOS or Android. More information: [Live Testing for Native Mobile Apps on Real Devic
```suggestion
A mobile software app written in a programming language specific to the platform it is being developed for: either iOS or Android. More information: [Live Testing for Native Mobile Apps on Real Devices](/mobile-apps/live-testing/live-mobile-app-testing), [Mobile App Testing with Espresso and XCUITest](/mobile-apps/automated-testing/espresso-xcuitest).
```

2021-08-12 23:34 UTC, spider-sauce commented on docs/mobile-apps/supported-devices.md
> +Our public cloud, available to all users regardless of pricing plan, contains a wide selection of thoroughly cleaned devices. They are subject to availability. On the mobile device selection screen,
```suggestion
Our public cloud, available to all users regardless of pricing plan, contains a wide selection of thoroughly cleaned devices. They are subject to availability. On the mobile device selection screen, if a device is in use, it'll be [marked with a **Busy** flag](/mobile-apps/live-testing/live-mobile-app-testing#selecting-a-real-device). Here are some use cases:
```

2021-08-12 23:34 UTC, spider-sauce commented on docs/overview.md
> +        <li><a href="/web-apps/automated-testing/selenium">Selenium</a> and <a href="mobile-apps/automated-testing/appium">Appium</a></li>
```suggestion
        <li><a href="/web-apps/automated-testing/selenium">Selenium</a> and <a href="/mobile-apps/automated-testing/appium">Appium</a></li>
```

2021-08-12 23:34 UTC, spider-sauce commented on docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
> +For instructions on how to run Sauce Connect Proxy on our Legacy RDC platform (TestObject), see [Creating a Sauce Connect Tunnel for Legacy Real Device Cloud](legacy-tunnels).
```suggestion
For instructions on how to run Sauce Connect Proxy on our Legacy RDC platform (TestObject), see [Creating a Sauce Connect Tunnel for Legacy Real Device Cloud](/secure-connections/sauce-connect/setup-configuration/legacy-tunnels/).
```

2021-08-13 00:34 UTC, sweeneyskirt-sl commented
Thanks for reviewing so quickly, @spider-sauce! Good catches. Hopefully that fixes the build I broke. LOL

2021-08-13 14:18 UTC, merged