Update test-status.md
saucelabs/sauce-docs pull request #839
Opened 2021-10-27 23:57 UTC by yavgel

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation fix (typos, incorrect content, missing content, etc.)

### Checklist

- [ ] I have read the [contributing](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-14 21:03 UTC, kimsauce commented on docs/test-results/test-status.md
> +```java reference title="Test Reporting with JUnit 4 Test Watcher"
@titusfortner @nikolay-advolodkin @diemol, we've received this Pull Request recommending we add a JUnit 4 example in addition to the existing ones (JUnit 5 and TestNG). Can you please take a look?

2022-04-15 17:04 UTC, titusfortner requested changes
Use this as the reference to match the others
https://github.com/saucelabs-training/demo-java/blob/docs-1.0/selenium-junit4-examples/src/test/java/com/saucedemo/selenium/junit4/demo/SeleniumTest.java#L55-L70

We can also created nested tabs for this if that's easier to read.

2022-08-12 12:39 UTC, lauramthomas commented on docs/test-results/test-status.md
> +```java reference title="Test Reporting with JUnit 4 Test Watcher"
@titusfortner @nikolay-advolodkin Following up on this open PR from April. Can you please check the JUnit 4 code sample added above for accuracy?

2022-08-15 14:47 UTC, nadvolod requested changes

2022-08-15 14:47 UTC, nadvolod commented on docs/test-results/test-status.md
> +```java reference title="Test Reporting with JUnit 4 Test Watcher"
@yavgel thanks so much for the excellent suggestion. The code is definitely correct. However, we don't reference code directly as it's subject to change and break. Instead we reference a release of the docs. In this case, this is the correct link to put 
https://github.com/saucelabs-training/demo-java/blob/a4f257e84c54897e20aa05ebe3d6d32a88755221/selenium-junit4-examples/src/test/java/com/saucedemo/selenium/junit4/demo/SeleniumTest.java#L55-L70

@lauramthomas if you just replace the code above with the link that I shared, similar to how [Junit5 reference code](https://github.com/saucelabs/sauce-docs/blob/659f5d75f80e5ee8b20494cf38b90d2ef34c0198/docs/test-results/test-status.md). Then this is correct.

2023-05-03 18:02 UTC, lysannep commented
@aliciakrebs Can you help with this PR?

2024-01-25 17:24 UTC, closed without merging